name: Minecord
version: '${project.version}'
main: me.bnsh.minecord.Main
api-version: '1.20'

commands:
  health:
    description: Sets health of player
  id:
    description: Sets the Guild-ID
  receive:
    description: Sets weather Discord can receive Minecraft messages or Minecraft can receive Discord messages
  whitelist:
    description: Add or remove player from whitelist